services:
  minio:
    image: minio/minio:latest
    container_name: kg_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./minio/data:/data
    restart: unless-stopped

  minio-init:
    image: minio/mc:latest
    container_name: kg_minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set local http://minio:9000 minioadmin minioadmin123;
      mc mb -p local/kg-raw-data || true;
      mc mb -p local/kg-preprocessed-data || true;
      mc mb -p local/kg-metadata || true;
      exit 0;
      "

  postgres:
    image: postgres:13
    container_name: kg_airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-db-volume:/var/lib/postgresql/data
    restart: unless-stopped

  airflow-init:
    user: "${AIRFLOW_UID}:0"
    group_add:
      - "${VBOXSF_GID}"
    image: apache/airflow:2.10.5
    container_name: kg_airflow_init
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: minio
    volumes:
      - airflow-dags-volume:/opt/airflow/dags
      - airflow-logs-volume:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /media/sf_KG_Thesis_Pipeline:/media/sf_KG_Thesis_Pipeline
    command: >
      bash -c "airflow db migrate &&
      airflow users create
      --username airflow
      --password airflow
      --firstname Rami
      --lastname Issa
      --role Admin
      --email airflow@example.com || true"

  airflow-webserver:
    user: "${AIRFLOW_UID}:0"
    group_add:
      - "${VBOXSF_GID}"
    image: apache/airflow:2.10.5
    container_name: kg_airflow_webserver
    depends_on:
      - airflow-init
      - postgres
      - minio
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: minio
    volumes:
      - airflow-dags-volume:/opt/airflow/dags
      - airflow-logs-volume:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /media/sf_KG_Thesis_Pipeline:/media/sf_KG_Thesis_Pipeline
    ports:
      - "8080:8080"
    command: webserver
    restart: unless-stopped

  airflow-scheduler:
    user: "${AIRFLOW_UID}:0"
    group_add:
      - "${VBOXSF_GID}"
    image: apache/airflow:2.10.5
    container_name: kg_airflow_scheduler
    depends_on:
      - airflow-init
      - postgres
      - minio
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _PIP_ADDITIONAL_REQUIREMENTS: minio
    volumes:
      - airflow-dags-volume:/opt/airflow/dags
      - airflow-logs-volume:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - /media/sf_KG_Thesis_Pipeline:/media/sf_KG_Thesis_Pipeline
    command: scheduler
    restart: unless-stopped

volumes:
  airflow-postgres-db-volume:
  airflow-logs-volume:
  airflow-dags-volume: